basePath: /swagger
definitions:
  main.Alarm:
    properties:
      id:
        type: integer
      message:
        type: string
      severity:
        type: string
      startTime:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Alarm server.
  title: Swagger Example API
  version: "1.0"
paths:
  /alarms:
    get:
      description: Get all alarms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Alarm'
            type: array
      summary: Get all alarms
  /clearAlarms/{id}:
    delete:
      description: Clear an alarm by ID
      parameters:
      - description: Alarm ID to be deleted
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Clear an alarm
  /generateAlarms:
    post:
      consumes:
      - application/json
      description: Generate a new alarm
      parameters:
      - description: Alarm object to be generated
        in: body
        name: alarm
        required: true
        schema:
          $ref: '#/definitions/main.Alarm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Alarm'
      summary: Generate an alarm
  /updateAlarms/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing alarm by ID
      parameters:
      - description: Alarm ID to be updated
        in: path
        name: id
        required: true
        type: integer
      - description: Updated alarm object
        in: body
        name: alarm
        required: true
        schema:
          $ref: '#/definitions/main.Alarm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Alarm'
      summary: Update an alarm
swagger: "2.0"
